nsionId":{"value":"formulahendry.auto-close-tag","_lower":"formulahendry.auto-close-tag"},"activationEvent":"*"}
[2020-02-17 09:25:55.067] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Administrator/.vscode/extensions/formulahendry.auto-close-tag-0.5.6/out/src/extension
[2020-02-17 09:25:55.121] [exthost] [info] ExtensionService#_doActivateExtension formulahendry.auto-rename-tag {"startup":true,"extensionId":{"value":"formulahendry.auto-rename-tag","_lower":"formulahendry.auto-rename-tag"},"activationEvent":"*"}
[2020-02-17 09:25:55.121] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Administrator/.vscode/extensions/formulahendry.auto-rename-tag-0.1.1/out/src/extension
[2020-02-17 09:25:55.312] [exthost] [info] ExtensionService#_doActivateExtension HookyQR.beautify {"startup":true,"extensionId":{"value":"HookyQR.beautify","_lower":"hookyqr.beautify"},"activationEvent":"*"}
[2020-02-17 09:25:55.312] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Administrator/.vscode/extensions/hookyqr.beautify-1.5.0/extension
[2020-02-17 09:25:58.552] [exthost] [info] ExtensionService#_doActivateExtension minhthai.vscode-todo-parser {"startup":true,"extensionId":{"value":"minhthai.vscode-todo-parser","_lower":"minhthai.vscode-todo-parser"},"activationEvent":"*"}
[2020-02-17 09:25:58.552] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Administrator/.vscode/extensions/minhthai.vscode-todo-parser-1.9.1/out/src/extension
[2020-02-17 09:25:58.985] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.sublime-keybindings {"startup":true,"extensionId":{"value":"ms-vscode.sublime-keybindings","_lower":"ms-vscode.sublime-keybindings"},"activationEvent":"*"}
[2020-02-17 09:25:58.985] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Administrator/.vscode/extensions/ms-vscode.sublime-keybindings-4.0.6/out/extension
[2020-02-17 09:25:59.172] [exthost] [info] ExtensionService#_doActivateExtension ritwickdey.LiveServer {"startup":true,"extensionId":{"value":"ritwickdey.LiveServer","_lower":"ritwickdey.liveserver"},"activationEvent":"*"}
[2020-02-17 09:25:59.172] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/Administrator/.v